# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1usQbppAAPjo-ATAAH9d3fAGjXzUQya5H
"""

#def remove_duplicates():
listA = [1,10,20,5,60,30,9,10]
listB = []
for x in listA:
    if x!=10:
      listB.append(x)
listB

list1 = ["A", "B", "C", "D", "E", "F"]
list2 = [1,2,3,4,5,6]
Dictionary = dict(zip(list1, list2))
Dictionary

person={
      "Name":"Quoc Nam",
      "Age": 28,
      "Salary":8000,
      "City":"Tuy Hoa"
}
KeyRemove=['Salary','City']
for x in KeyRemove:
    if x in person:
      person.pop(x)
person

import numpy as np
from google.colab import drive
drive.mount('/content/drive')

#4a